#!/bin/bash

# A simple sketchybar config for aerospace users to get started with
# Not too different from the base starting config!
PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 color=$TRANSPARENT

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="SF Pro:Semibold:17.0"
  icon.color=$TEXT_WHITE
  label.color=$TEXT_WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  updates=on
  y_offset=-3
)
sketchybar --default "${default[@]}"

sketchybar --add item spacePaddingLeft left --set spacePaddingLeft padding_left=-18

##### Adding aeropsace layouts #####
# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change

# This only works for single monitor configs!
for sid in $(aerospace list-workspaces --monitor 1); do
  #for sid in "${SPACE_IDS[@]}"; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    drawing=off \
    background.corner_radius=5 \
    background.drawing=on \
    background.border_width=1 \
    background.height=23 \
    background.padding_right=5 \
    background.padding_left=5 \
    icon="$sid" \
    icon.shadow.drawing=off \
    icon.padding_left=10 \
    label.font="sketchybar-app-font:Regular:16.0" \
    label.padding_right=20 \
    label.padding_left=0 \
    label.y_offset=-1 \
    label.shadow.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Load Icons on startup
for sid in $(aerospace list-workspaces --monitor 1 --empty no); do
  apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

  sketchybar --set space.$sid drawing=on

  icon_strip=" "
  if [ "${apps}" != "" ]; then
    while read -r app; do
      icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
    done <<<"${apps}"
  else
    icon_strip=""
  fi
  sketchybar --set space.$sid label="$icon_strip"
done

sketchybar --add item spacePaddingRight left --set spacePaddingRight padding_left=-18

sketchybar --add item space_separator q \
  --set space_separator icon="" \
  icon.padding_left=20 \
  icon.padding_right=0 \
  icon.margin_right=0 \
  label.drawing=off \
  label.padding_left=0 \
  label.margin_left=0 \
  background.drawing=off \
  script="$PLUGIN_DIR/space_windows.sh" \
  --subscribe space_separator aerospace_workspace_change space_windows_change front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other gititems respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
  \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  \
  --add item wifi right \
  --set wifi script="$PLUGIN_DIR/wifi.sh" label.font="SF Pro:Italic:12.0" label.y_offset=-3 \
  popup.background.color=$BACKGROUND \
  popup.background.border_width=2 \
  popup.background.border_color=$TEXT_WHITE \
  popup.background.corner_radius=10 \
  popup.y_offset=5 \
  --subscribe wifi wifi_change mouse.entered mouse.exited \
  \
  --add item wifi.priv.addr popup.wifi \
  --set wifi.priv.addr icon="󰌗" \
  \
  --add item wifi.pub.addr popup.wifi \
  --set wifi.pub.addr icon="󰖟" \
  \
  --add item swap e \
  --set swap update_freq=20 script="$PLUGIN_DIR/memswap.sh" \
  icon="" \
  label.font="Hack Nerd Font:Italic:13.0" \
  icon.padding_left=8 \
  label.padding_right=8 \
  click_script="open -a 'Activity Monitor'" \
  \
  --add alias Stats e --set Stats label.padding_left=0 label.padding_right=0 icon.padding_left=0 icon.padding_right=0 alias.update_freq=3

#### Groups !!! ####
sketchybar --add bracket spaces '/space\..*/' spacePaddingLeft spacePaddingRight \
  --set spaces background.color=$BACKGROUND \
  background.corner_radius=10 \
  background.height=30

sketchybar --add bracket statsDisplay swap Stats \
  --set statsDisplay \
  background.color=$BACKGROUND_DARK \
  background.corner_radius=10 \
  background.drawing=on \
  background.height=30 #$TEXT_GREY \

sketchybar --add bracket rightItems clock volume battery wifi \
  --set rightItems background.color=$BACKGROUND \
  background.corner_radius=10 \
  background.height=30

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
